package vista;

import controlador.Empresa;
import javax.swing.JOptionPane;

public class Ventana2 extends javax.swing.JFrame {

    private PanelAlta panelAlta;
    private PanelConsulta panelConsulta;
    private Empresa empresa;

    public Ventana2() {
        initComponents();
    }

    public Ventana2(String nomUsuario, Empresa empresa) {
        initComponents();
        this.setTitle(nomUsuario);
        this.empresa = empresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsuarios = new javax.swing.JMenu();
        mnuAlta = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mnuDesconectar = new javax.swing.JMenuItem();
        mnuFin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        mnuUsuarios.setText("Usuaios");

        mnuAlta.setText("Alta de usuarios");
        mnuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuAlta);

        mnuConsulta.setText("Consulta");
        mnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuConsulta);

        jMenuBar1.add(mnuUsuarios);

        mnuSalir.setText("Salir");

        mnuDesconectar.setText("Desconectar");
        mnuDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDesconectarActionPerformed(evt);
            }
        });
        mnuSalir.add(mnuDesconectar);

        mnuFin.setText("Fin de la aplicación");
        mnuFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFinActionPerformed(evt);
            }
        });
        mnuSalir.add(mnuFin);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDesconectarActionPerformed
        new Ventana(empresa).setVisible(true);
        this.dispose();
        pack();
    }//GEN-LAST:event_mnuDesconectarActionPerformed

    private void mnuFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFinActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuFinActionPerformed

    private void mnuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaActionPerformed
        eliminarPaneles();
        panelAlta = new PanelAlta(empresa);
        getContentPane().add(panelAlta);
        pack();
    }//GEN-LAST:event_mnuAltaActionPerformed

    private void mnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaActionPerformed
        eliminarPaneles();
        panelConsulta = new PanelConsulta(empresa);
        getContentPane().add(panelConsulta);
        pack();
    }//GEN-LAST:event_mnuConsultaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opcion = JOptionPane.showConfirmDialog(this, "¿Realmente quiere salir?");
        if (opcion == JOptionPane.OK_OPTION) {
            dispose();
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_formWindowClosing
    private void eliminarPaneles() {
        try {
            this.remove(panelAlta);
        } catch (Exception ex) {
        }
        try {
            this.remove(panelConsulta);
        } catch (Exception ex) {
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAlta;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuDesconectar;
    private javax.swing.JMenuItem mnuFin;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
